apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web-app-{{.Values.version}}
  labels:
    app: demo-web-app-{{.Values.version}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-web-app-{{.Values.version}}
  template:
    metadata:
      labels:
        app: demo-web-app-{{.Values.version}}
    spec:
      containers:
      - name: demo-web-app-{{.Values.version}}
        image: "{{ .Values.image -}}:{{- .Values.version | default "latest" }}"
        env:
        - name: VERSION
          value: {{ .Values.version }}
        ports:
        - containerPort: 8080
